name: Main Extension Distribution Pipeline
on:
  push:
    branches:
    - v2.0
  pull_request: null
  workflow_dispatch: null
  schedule:
  - cron: 0 2 * * *
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{
    github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: v2.0-cyanoptera
      ci_tools_version: main
      extension_name: shellfs
      exclude_archs: wasm_mvp;wasm_eh;wasm_threads
